export const POI_TYPE = [
    {id:0,eng:'Undefined'},
    {id:1,eng:'Capital'},
    {id:11,eng:'Mayor city (> 500.000)'},
    {id:12,eng:'Large city (100.000 - 500.000)'},
    {id:13,eng:'City (50.000 - 100.000)'},
    {id:14,eng:'Town (10.000 - 50.000)'},
    {id:15,eng:'Small town (5.000 - 10.000)'},
    {id:16,eng:'Village (1.000 - 5.000)'},
    {id:17,eng:'Small village (< 1.000)'},
    {id:18,eng:'City part'},
    {id:40,eng:'Island generic'},
    {id:41,eng:'Huge island'},
    {id:42,eng:'Large island'},
    {id:43,eng:'Medium island'},
    {id:44,eng:'Small island'},
    {id:45,eng:'Tiny island'},
    {id:46,eng:'Rocks'},
    {id:80,eng:'Square'},
    {id:170,eng:'Toll Booth/Gate'},
    {id:300,eng:'Border crossing'},
    {id:301,eng:'American food'},
    {id:302,eng:'Californian food'},
    {id:303,eng:'Chinese food'},
    {id:304,eng:'Continental food'},
    {id:305,eng:'French food'},
    {id:306,eng:'German food'},
    {id:307,eng:'Greek food'},
    {id:308,eng:'Indian food'},
    {id:309,eng:'Italian food'},
    {id:310,eng:'Japanese food'},
    {id:311,eng:'Mexican food'},
    {id:312,eng:'Seafood'},
    {id:313,eng:'Thai food'},
    {id:314,eng:'Vegetarian food'},
    {id:315,eng:'Vietnamese food'},
    {id:316,eng:'Austrian food'},
    {id:317,eng:'Barbecue/Southern'},
    {id:318,eng:'Belgian food'},
    {id:319,eng:'Bistro'},
    {id:320,eng:'Brewpub'},
    {id:321,eng:'British Isles food'},
    {id:322,eng:'Dutch food'},
    {id:323,eng:'East European food'},
    {id:325,eng:'Grill'},
    {id:326,eng:'Hawaiian/Polynesian food'},
    {id:327,eng:'Hungarian food'},
    {id:328,eng:'Indonesian/Malaysian food'},
    {id:329,eng:'Jewish/kosher food'},
    {id:330,eng:'Korean food'},
    {id:331,eng:'Latin American food'},
    {id:332,eng:'Maltese food'},
    {id:333,eng:'Middle Eastern food'},
    {id:334,eng:'Filipino food'},
    {id:335,eng:'Polish food'},
    {id:336,eng:'Portuguese food'},
    {id:337,eng:'Russian food'},
    {id:338,eng:'Sandwich'},
    {id:339,eng:'Scandinavian food'},
    {id:340,eng:'South American food'},
    {id:341,eng:'Southeast Asian food'},
    {id:342,eng:'Southwestern food'},
    {id:343,eng:'Surinamese food'},
    {id:344,eng:'Spanish food'},
    {id:345,eng:'Steak house'},
    {id:346,eng:'Swiss food'},
    {id:347,eng:'Turkish food'},
    {id:348,eng:'African food'},
    {id:349,eng:'Canadian food'},
    {id:350,eng:'International food'},
    {id:351,eng:'Bohemian food'},
    {id:352,eng:'Balkan food'},
    {id:353,eng:'Finnish food'},
    {id:354,eng:'Australian food'},
    {id:355,eng:'Pizza'},
    {id:356,eng:'Snacks and beverages'},
    {id:357,eng:'Breakfast'},
    {id:358,eng:'Chicken'},
    {id:359,eng:'Ice cream'},
    {id:360,eng:'Tapas'},
    {id:361,eng:'Irish food'},
    {id:362,eng:'Caribbean food'},
    {id:363,eng:'Malaysian food'},
    {id:364,eng:'Moroccan food'},
    {id:365,eng:'Fusion'},
    {id:366,eng:'Brazilian food'},
    {id:367,eng:'Creole food'},
    {id:368,eng:'Burgers'},
    {id:369,eng:'Creperie'},
    {id:370,eng:'Pastries'},
    {id:371,eng:'Sushi'},
    {id:372,eng:'Vegan food'},
    {id:373,eng:'Cajun food'},
    {id:374,eng:'Indonesian food'},
    {id:375,eng:'Fondue'},
    {id:376,eng:'Argentinean food'},
    {id:377,eng:'Chilean food'},
    {id:378,eng:'Azerbaijan food'},
    {id:379,eng:'Baltic food'},
    {id:380,eng:'Caucasian food'},
    {id:381,eng:'Ukrainian food'},
    {id:382,eng:'Venezuelan food'},
    {id:383,eng:'Bruneian food'},
    {id:400,eng:'Tourist information'},
    {id:401,eng:'Tourist office'},
    {id:402,eng:'Museum'},
    {id:403,eng:'Historical monument'},
    {id:404,eng:'Tourist attraction building'},
    {id:405,eng:'Natural attraction'},
    {id:406,eng:'Tourist attraction'},
    {id:407,eng:'Recreation facility'},
    {id:408,eng:'Amusement park'},
    {id:409,eng:'Castle'},
    {id:410,eng:'School'},
    {id:411,eng:'University or college'},
    {id:412,eng:'Library'},
    {id:413,eng:'Kindergarten'},
    {id:414,eng:'Institute'},
    {id:415,eng:'Campus'},
    {id:416,eng:'Educational religion institute'},
    {id:420,eng:'Culture generic'},
    {id:421,eng:'Theatre'},
    {id:422,eng:'Casino'},
    {id:423,eng:'Nightlife'},
    {id:424,eng:'Entertainment'},
    {id:425,eng:'Zoo'},
    {id:426,eng:'Cinema'},
    {id:427,eng:'Opera'},
    {id:428,eng:'Leisure'},
    {id:429,eng:'Gallery'},
    {id:430,eng:'Business facility'},
    {id:431,eng:'Company'},
    {id:432,eng:'Building footprint'},
    {id:433,eng:'Services'},
    {id:434,eng:'Laundry dry cleaning'},
    {id:435,eng:'Hair beauty'},
    {id:440,eng:'Exhibition conference'},
    {id:441,eng:'Events'},
    {id:450,eng:'Hotel/motel'},
    {id:451,eng:'Hotel'},
    {id:452,eng:'Motel'},
    {id:453,eng:'Camping ground'},
    {id:454,eng:'Convention center'},
    {id:459,eng:'Other accommodation'},
    {id:460,eng:'Restaurant'},
    {id:461,eng:'Cafe'},
    {id:462,eng:'Banquet and marriage hall'},
    {id:463,eng:'Fast food'},
    {id:464,eng:'Coffee shop'},
    {id:465,eng:'Bar'},
    {id:470,eng:'Shopping center'},
    {id:471,eng:'Grocery store'},
    {id:472,eng:'Winery'},
    {id:473,eng:'Market'},
    {id:474,eng:'Florist'},
    {id:475,eng:'Clothing store'},
    {id:476,eng:'Home specialty store'},
    {id:477,eng:'Specialty store'},
    {id:478,eng:'Sporting goods store'},
    {id:479,eng:'Home improvement and hardware store'},
    {id:480,eng:'Stadium'},
    {id:481,eng:'Sports activity'},
    {id:482,eng:'Ski resort'},
    {id:483,eng:'Golf course'},
    {id:484,eng:'Bowling center'},
    {id:485,eng:'Ice skating rink'},
    {id:486,eng:'Sports center'},
    {id:487,eng:'Sports hall'},
    {id:488,eng:'Swimming pool'},
    {id:489,eng:'Tennis court'},
    {id:490,eng:'Nature'},
    {id:491,eng:'Mountain pass'},
    {id:492,eng:'Mountain peak'},
    {id:493,eng:'Beach'},
    {id:494,eng:'Bay'},
    {id:500,eng:'Government office'},
    {id:501,eng:'City hall'},
    {id:502,eng:'Police station'},
    {id:503,eng:'State police office'},
    {id:504,eng:'Court house'},
    {id:506,eng:'Embassy'},
    {id:507,eng:'Fire station'},
    {id:508,eng:'Neighbour district'},
    {id:509,eng:'Public restroom'},
    {id:510,eng:'Recycling centre'},
    {id:511,eng:'Prison'},
    {id:530,eng:'City feature'},
    {id:531,eng:'Community centre'},
    {id:532,eng:'Cemetery'},
    {id:533,eng:'Park'},
    {id:534,eng:'City centre'},
    {id:535,eng:'Sport club'},
    {id:536,eng:'Retirement home'},
    {id:540,eng:'Church'},
    {id:541,eng:'Mosque'},
    {id:542,eng:'Temple'},
    {id:543,eng:'Synagogue'},
    {id:560,eng:'Hospital'},
    {id:561,eng:'Doctor'},
    {id:562,eng:'Pharmacy'},
    {id:563,eng:'Dentist'},
    {id:564,eng:'Veterinarian'},
    {id:565,eng:'Ambulance'},
    {id:567,eng:'Familiy general practice'},
    {id:568,eng:'Clinic medical centre'},
    {id:569,eng:'Optician'},
    {id:570,eng:'Post office'},
    {id:571,eng:'Main post office'},
    {id:572,eng:'Minor post office'},
    {id:580,eng:'Bank'},
    {id:581,eng:'ATM'},
    {id:582,eng:'Money exchange'},
    {id:590,eng:'Industry facility'},
    {id:600,eng:'Vehicle repair facility'},
    {id:601,eng:'Vehicle technical check station'},
    {id:602,eng:'Car wash'},
    {id:603,eng:'Auto parts'},
    {id:604,eng:'Car repair'},
    {id:605,eng:'Truck repair'},
    {id:606,eng:'Tire repair'},
    {id:610,eng:'Petrol station'},
    {id:611,eng:'LPG station'},
    {id:612,eng:'Electric charge station'},
    {id:620,eng:'Rent-a-car facility'},
    {id:630,eng:'Parking'},
    {id:631,eng:'Garage parking'},
    {id:632,eng:'Garage parking P&R'},
    {id:633,eng:'Open parking'},
    {id:634,eng:'Open parking P&R'},
    {id:635,eng:'Rent-a-car parking'},
    {id:636,eng:'Park and ride'},
    {id:637,eng:'Commuter rail station'},
    {id:640,eng:'Railway station'},
    {id:641,eng:'Main railway station'},
    {id:642,eng:'Minor railway station'},
    {id:643,eng:'Metro station'},
    {id:644,eng:'Bus station'},
    {id:645,eng:'Suburban'},
    {id:646,eng:'Tram stop'},
    {id:647,eng:'Bus stop'},
    {id:650,eng:'Airport'},
    {id:651,eng:'Civil airport'},
    {id:652,eng:'Military airport'},
    {id:653,eng:'Public sport airport'},
    {id:654,eng:'Airport terminal'},
    {id:660,eng:'Rest area'},
    {id:670,eng:'Car dealer'},
    {id:671,eng:'Car dealer - sales'},
    {id:672,eng:'Car dealer - repair'},
    {id:673,eng:'Car dealer - sales and repair'},
    {id:674,eng:'Motoring organization office'},
    {id:675,eng:'Motorcycle dealer'},
    {id:676,eng:'Truck dealer'},
    {id:680,eng:'Ferry terminal'},
    {id:681,eng:'Marina'},
    {id:682,eng:'Harbour'},
    {id:683,eng:'Quay'},
    {id:690,eng:'Lighthouse'},
    {id:695,eng:'Fix radar (speed camera)'},
    {id:696,eng:'Mobile radar (speed camera)'},
    {id:697,eng:'Red light'},
    {id:698,eng:'Average speed'},
    {id:699,eng:'Generic poi'},
    {id:720,eng:'Consumer electronics store'},
    {id:721,eng:'Office supply and services store'},
    {id:722,eng:'Furniture shop'},
    {id:723,eng:'Book store'},
    {id:724,eng:'Kiosk'},
    {id:725,eng:'Fitness health club'},
    {id:726,eng:'Soccer club'},
    {id:727,eng:'Ski lift'},
    {id:728,eng:'Archaeological site'},
    {id:729,eng:'Big grocery store'},
    {id:873,eng:'Taxi station'},
    {id:921,eng:'Freeway exit'},
    {id:922,eng:'Freeway interchange'},
  ] 